### ISSUE TITLE
Submit the draft version 

### ISSUE THREAD

**Issue by ValerioMedeiros** [ValerioMedeiros/felipy#1]
Submit the draft version of the web editor without a backend. 
To publish on a webpage, we can use the branch gh-pages, similar to the approach of mkdocs.

**Comment by adorilson** [comment]
@vadolasi Can you improvement the [First Step](https://github.com/ValerioMedeiros/felipy/blob/main/docs/index.md)?

Or is it done?

**Comment by adorilson** [comment]
I try to run (on Ubuntu 20.04.4 LTS)  and got the follow:

```
$ npm install

> esbuild@0.14.39 postinstall /home/adorilson/workspace/felpy/web-editor/node_modules/esbuild
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for @vitejs/plugin-react@1.3.2: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @vitejs/plugin-react@1.3.2
npm WARN notsup Unsupported engine for eslint@8.16.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: eslint@8.16.0
npm WARN notsup Unsupported engine for eslint-plugin-n@15.2.0: wanted: {"node":">=12.22.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: eslint-plugin-n@15.2.0
npm WARN notsup Unsupported engine for eslint-plugin-promise@6.0.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: eslint-plugin-promise@6.0.0
npm WARN notsup Unsupported engine for unocss@0.33.5: wanted: {"node":">=14"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: unocss@0.33.5
npm WARN notsup Unsupported engine for vite@2.9.9: wanted: {"node":">=12.2.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: vite@2.9.9
npm WARN notsup Unsupported engine for @typescript-eslint/parser@5.26.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/parser@5.26.0
npm WARN notsup Unsupported engine for @typescript-eslint/eslint-plugin@5.26.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/eslint-plugin@5.26.0
npm WARN notsup Unsupported engine for @typescript-eslint/utils@5.26.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/utils@5.26.0
npm WARN notsup Unsupported engine for @typescript-eslint/type-utils@5.26.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/type-utils@5.26.0
npm WARN notsup Unsupported engine for @typescript-eslint/scope-manager@5.26.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/scope-manager@5.26.0
npm WARN notsup Unsupported engine for @typescript-eslint/visitor-keys@5.26.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/visitor-keys@5.26.0
npm WARN notsup Unsupported engine for @typescript-eslint/types@5.26.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/types@5.26.0
npm WARN notsup Unsupported engine for eslint-visitor-keys@3.3.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: eslint-visitor-keys@3.3.0
npm WARN notsup Unsupported engine for @typescript-eslint/typescript-estree@5.26.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/typescript-estree@5.26.0
npm WARN notsup Unsupported engine for @eslint/eslintrc@1.3.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @eslint/eslintrc@1.3.0
npm WARN notsup Unsupported engine for eslint-scope@7.1.1: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: eslint-scope@7.1.1
npm WARN notsup Unsupported engine for espree@9.3.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: espree@9.3.2
npm WARN notsup Unsupported engine for @unocss/cli@0.33.5: wanted: {"node":">=14"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @unocss/cli@0.33.5
npm WARN notsup Unsupported engine for @unocss/config@0.33.5: wanted: {"node":">=14"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @unocss/config@0.33.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for local-pkg@0.4.1: wanted: {"node":">=14"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: local-pkg@0.4.1
npm WARN notsup Unsupported engine for undici@5.3.0: wanted: {"node":">=12.18"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: undici@5.3.0
npm WARN notsup Unsupported engine for css-tree@2.1.0: wanted: {"node":"^10 || ^12.20.0 || ^14.13.0 || >=15.0.0","npm":">=7.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: css-tree@2.1.0
npm WARN notsup Unsupported engine for magic-string@0.26.2: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: magic-string@0.26.2
npm WARN notsup Unsupported engine for esbuild@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild@0.14.39
npm WARN notsup Unsupported engine for esbuild-android-64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-android-64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-64@0.14.39 (node_modules/esbuild/node_modules/esbuild-android-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-64@0.14.39: wanted {"os":"android","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-android-arm64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-android-arm64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.14.39 (node_modules/esbuild/node_modules/esbuild-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.14.39: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-darwin-64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-darwin-64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-64@0.14.39 (node_modules/esbuild/node_modules/esbuild-darwin-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-64@0.14.39: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-darwin-arm64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-darwin-arm64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.14.39 (node_modules/esbuild/node_modules/esbuild-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.14.39: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-freebsd-64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-freebsd-64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.14.39 (node_modules/esbuild/node_modules/esbuild-freebsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.14.39: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-freebsd-arm64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-freebsd-arm64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.14.39 (node_modules/esbuild/node_modules/esbuild-freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.14.39: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-linux-32@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-32@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.14.39 (node_modules/esbuild/node_modules/esbuild-linux-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.14.39: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-linux-64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-64@0.14.39
npm WARN notsup Unsupported engine for esbuild-linux-arm@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-arm@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.14.39 (node_modules/esbuild/node_modules/esbuild-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.14.39: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-linux-arm64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-arm64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm64@0.14.39 (node_modules/esbuild/node_modules/esbuild-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm64@0.14.39: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-linux-mips64le@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-mips64le@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-mips64le@0.14.39 (node_modules/esbuild/node_modules/esbuild-linux-mips64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-mips64le@0.14.39: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-linux-ppc64le@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-ppc64le@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-ppc64le@0.14.39 (node_modules/esbuild/node_modules/esbuild-linux-ppc64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-ppc64le@0.14.39: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-linux-riscv64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-riscv64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-riscv64@0.14.39 (node_modules/esbuild/node_modules/esbuild-linux-riscv64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-riscv64@0.14.39: wanted {"os":"linux","arch":"riscv64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-linux-s390x@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-s390x@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-s390x@0.14.39 (node_modules/esbuild/node_modules/esbuild-linux-s390x):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-s390x@0.14.39: wanted {"os":"linux","arch":"s390x"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-netbsd-64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-netbsd-64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-netbsd-64@0.14.39 (node_modules/esbuild/node_modules/esbuild-netbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-netbsd-64@0.14.39: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-openbsd-64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-openbsd-64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-openbsd-64@0.14.39 (node_modules/esbuild/node_modules/esbuild-openbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-openbsd-64@0.14.39: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-sunos-64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-sunos-64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-sunos-64@0.14.39 (node_modules/esbuild/node_modules/esbuild-sunos-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-sunos-64@0.14.39: wanted {"os":"sunos","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-windows-32@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-windows-32@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-32@0.14.39 (node_modules/esbuild/node_modules/esbuild-windows-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-32@0.14.39: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-windows-arm64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-windows-arm64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-arm64@0.14.39 (node_modules/esbuild/node_modules/esbuild-windows-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-arm64@0.14.39: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for esbuild-windows-64@0.14.39: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esbuild-windows-64@0.14.39
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-64@0.14.39 (node_modules/esbuild/node_modules/esbuild-windows-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-64@0.14.39: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for pretty-bytes@6.0.0: wanted: {"node":"^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: pretty-bytes@6.0.0
npm WARN @apideck/better-ajv-errors@0.3.4 requires a peer of ajv@>=8 but none is installed. You must install peer dependencies yourself.

added 559 packages from 298 contributors and audited 579 packages in 352.582s

114 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npm run dev

> web-editor@0.0.0 dev /home/adorilson/workspace/felpy/web-editor
> vite --host 0.0.0.0

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/adorilson/workspace/felpy/web-editor/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:25:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-editor@0.0.0 dev: `vite --host 0.0.0.0`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-editor@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adorilson/.npm/_logs/2022-05-26T14_07_05_455Z-debug.log

```

**Comment by adorilson** [comment]
I tried Ubuntu 22.04 and got other errors:

```
$ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'unocss@0.33.5',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@unocss/cli@0.33.5',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@unocss/config@0.33.5',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'local-pkg@0.4.1',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pretty-bytes@6.0.0',
npm WARN EBADENGINE   required: { node: '^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

added 558 packages, and audited 559 packages in 3m

114 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npm run dev

> web-editor@0.0.0 dev
> vite --host 0.0.0.0

failed to load config from /home/adorilson/workspace/felipy/web-editor/vite.config.ts
error when starting dev server:
/home/adorilson/workspace/felipy/web-editor/node_modules/@unocss/vite/dist/index.cjs:295
        return command === "build" && !options.build?.ssr;
                                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/adorilson/workspace/felipy/web-editor/node_modules/unocss/dist/vite.cjs:5:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

**Comment by vadolasi** [comment]
What is your node.js version?

**Comment by adorilson** [comment]
> What is your node.js version?

$ node -v
v12.22.9

It is in Ubuntu 22.04.

Now I realized that must be >=14. 
I have updated to this, and after to 16.
In both cases,`npm run dev` command works.

```
$ node -v
v16.15.0
$ npm run dev

> web-editor@0.0.0 dev
> vite --host 0.0.0.0


  vite v2.9.9 dev server running at:

  > Local:    http://localhost:3000/
  > Network:  http://192.168.0.5:3000/
  > Network:  http://172.18.0.1:3000/

  ready in 201ms.

```

However, when I open `http://localhost:3000/` the app load, but not works properly.
In the JavaScript console, I got the follow:

Firefox:
![image](https://user-images.githubusercontent.com/169837/170831030-ae21ad68-a5d2-4132-9356-3646036bd1cc.png)

Chromium:
![image](https://user-images.githubusercontent.com/169837/170831110-f8261cbc-f15e-48a4-a3cb-bddc353d2d37.png)

**Comment by vadolasi** [comment]
> > What is your node.js version?
> 
> $ node -v v12.22.9
> 
> It is in Ubuntu 22.04.
> 
> Now I realized that must be >=14. I have updated to this, and after to 16. In both cases,`npm run dev` command works.
> 
> ```
> $ node -v
> v16.15.0
> $ npm run dev
> 
> > web-editor@0.0.0 dev
> > vite --host 0.0.0.0
> 
> 
>   vite v2.9.9 dev server running at:
> 
>   > Local:    http://localhost:3000/
>   > Network:  http://192.168.0.5:3000/
>   > Network:  http://172.18.0.1:3000/
> 
>   ready in 201ms.
> ```
> 
> However, when I open `http://localhost:3000/` the app load, but not works properly. In the JavaScript console, I got the follow:
> 
> Firefox: ![image](https://user-images.githubusercontent.com/169837/170831030-ae21ad68-a5d2-4132-9356-3646036bd1cc.png)
> 
> Chromium: ![image](https://user-images.githubusercontent.com/169837/170831110-f8261cbc-f15e-48a4-a3cb-bddc353d2d37.png)

This error has been fixed. If there is another problem, please open a new issue.
